language: ruby
rvm:
  - 2.1.1

env:
  - DB=sqlite
  - DB=postgresql  

branches:
  only:
    - master

bundler_args: --without development:production --path vendor/bundle

before_install:
  - gem update --system
  - gem --version
  - gem update bundler

script:
  #- RAILS_ENV=test bundle exec rake db:create db:migrate db:populate spec
  - RAILS_ENV=test bundle exec rake --trace db:migrate db:populate
  - bundle exec rake db:test:prepare
  - bundle exec rspec spec/

before_script:
  - psql -c 'create database chirper_production' -U user  
